name: TalkingHeadBubble
options:
  bundleIdPrefix: com.talkingheadbubble
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

targets:
  TalkingHeadBubble:
    type: application
    platform: macOS
    sources:
      - Sources
    settings:
      base:
        SWIFT_VERSION: "6.0"
        INFOPLIST_FILE: Sources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Sources/TalkingHeadBubble.entitlements
        CODE_SIGN_IDENTITY: "-"
        PRODUCT_BUNDLE_IDENTIFIER: com.talkingheadbubble.app
        GENERATE_INFOPLIST_FILE: false
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
